local map = vim.keymap.set
map("n", "<leader>e", "<cmd>Neotree toggle<CR>", { desc = "Explorer" })
map("n", "<leader>ff", "<cmd>Telescope find_files<CR>", { desc = "Find files" })
map("n", "<leader>fr", "<cmd>Telescope oldfiles<CR>", { desc = "Recent files" })
map("n", "<leader>fg", "<cmd>Telescope live_grep<CR>", { desc = "Search text" })
map("n", "<leader>bb", "<cmd>Telescope buffers<CR>", { desc = "Buffers" })
map("n", "<leader>bl", "<cmd>BufferLinePick<CR>", { desc = "Pick buffer" })
map("n", "<leader>bd", "<cmd>bdelete<CR>", { desc = "Close buffer" })
map("n", "<leader>gg", "<cmd>Lazy<CR>", { desc = "Plugin manager" })
map("n", "<leader>tt", "<cmd>ToggleTerm<CR>", { desc = "Terminal" })
map("n", "<leader>wr", function() require("persistence").load() end, { desc = "Restore session" })
map("n", "<leader>wl", function() require("persistence").load({ last = true }) end, { desc = "Restore last session" })
map("n", "<C-h>", "<C-w>h")
map("n", "<C-j>", "<C-w>j")
map("n", "<C-k>", "<C-w>k")
map("n", "<C-l>", "<C-w>l")
