vim.diagnostic.config({ virtual_text = false, float = { border = "rounded", source = true }, severity_sort = true, update_in_insert = false })
local capabilities = require("cmp_nvim_lsp").default_capabilities()
require("mason").setup()
require("mason-lspconfig").setup({ handlers = { function(server) require("lspconfig")[server].setup({ capabilities = capabilities }) end } })
vim.api.nvim_create_autocmd("LspAttach", { callback = function(event)
  local opts = { buffer = event.buf }
  map = vim.keymap.set
  map("n", "gd", vim.lsp.buf.definition, opts)
  map("n", "gr", vim.lsp.buf.references, opts)
  map("n", "K", vim.lsp.buf.hover, opts)
  map("n", "[d", vim.diagnostic.goto_prev, opts)
  map("n", "]d", vim.diagnostic.goto_next, opts)
  map("n", "<leader>rn", vim.lsp.buf.rename, opts)
  map({ "n", "v" }, "<leader>ca", vim.lsp.buf.code_action, opts)
end })
